### ISSUE TITLE
from utils.utils import create_config "No Module named 'utils'"

### ISSUE THREAD

**Issue by jabowery** [abr/neurips2019#9]
http://localhost:8888/notebooks/experiments/psMNIST-phased-lstm.ipynb

Does:

`from utils.utils import create_config`

resulting in an error:

`ModuleNotFoundError: No module named 'utils'`

It is unclear what python module this refers to.

**Comment by arvoelke** [comment]
Thanks for reporting this. Try running:

```
git submodule update --init --recursive
```

from the project directory. This should populate the `nru` directory with the submodule that we're trying to dynamically import here. Let me know if this fixes the problem, and then I'll add this to the installation instructions.

**Comment by jabowery** [comment]
Yes, that resolve the issue.
